### PR TITLE
Rspec

### PR DESCRIPTION
**Pull request by edwinmoradian90**

### CODE REVIEW

**Comment by fabricio-garcia** [comment]
Hello @whiz25 thank you for the review. We already tested the cases for the enumerable project few days ago and submitted that project. You can check that out here: https://github.com/edwinmoradian90/enum-methods/pull/5. That project was approved already.

**Comment by whiz25** [comment]
I am sorry for the confusion @fabricio-garcia. The project description states that the tests are for two projects not one that's why I requested that change. Anyways, all you can do now is to resubmit and make it clear that this is the second part of the review and the first one is already approved.
Let me know of anything.

**Comment by edwinmoradian90** [comment]
Ok resubmitted, and just for clarity, we did enumerable first because we were waiting for the review of the tic-tac-toe project to start on the rspec for tic-tac-toe.

**Comment by edwinmoradian90** [comment]
Cool thanks

**Pull request merged**
